import { beforeEach, describe, expect, it, vi } from "vitest";

import {
  campaignScheduleRouter,
  resolveCampaignSchedulePayload,
} from "@/server/api/routers/campaign/schedule";
import {
  getCampaignForMemberById,
  listCampaignOccurrenceOverrides,
  upsertCampaignOccurrenceOverride,
} from "@/server/db/queries/campaign";
import { serializeRecurrence } from "@/server/domain/campaign/schedule";
import { testContext } from "@/test/context";

vi.mock("@/server/db/queries/campaign", () => ({
  clearCampaignSchedule: vi.fn(),
  getCampaignForMemberById: vi.fn(),
  listCampaignOccurrenceOverrides: vi.fn(),
  removeCampaignOccurrenceOverride: vi.fn(),
  setCampaignSchedule: vi.fn(),
  upsertCampaignOccurrenceOverride: vi.fn(),
}));

const campaignId = "11111111-1111-4111-8111-111111111111";
const startAt = new Date("2026-08-08T23:00:00Z");
const campaign = {
  id: campaignId,
  name: "Saturday Table",
  slug: "saturday-table",
  status: "active",
  recurrence: serializeRecurrence({
    freq: "WEEKLY",
    interval: 1,
    byDay: ["SA"],
  }),
  recurrenceStartAt: startAt,
  recurrenceTimeZone: "America/New_York",
  recurrenceDurationMinutes: 180,
  memberId: "member-1",
  memberRole: "dm",
  memberSince: new Date("2026-01-01T00:00:00Z"),
};
const session = {
  user: { id: "dm-1", name: "DM", email: "dm@example.com" },
  session: { id: "session-1" },
} as never;

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(getCampaignForMemberById).mockResolvedValue(campaign as never);
  vi.mocked(listCampaignOccurrenceOverrides).mockResolvedValue([]);
});

describe("campaign schedule router", () => {
  it("returns structured recurrence and never exposes the raw RRULE", async () => {
    const caller = campaignScheduleRouter.createCaller(
      testContext(vi.fn(), session),
    );

    const result = await caller.get({ campaignId });

    expect(result.recurrence).toEqual({
      freq: "WEEKLY",
      interval: 1,
      byDay: ["SA"],
    });
    expect(result).not.toHaveProperty("rawRecurrence");
    expect(result.occurrences.length).toBeGreaterThan(0);
  });

  it("rejects an orphan override that is not generated by the rule", async () => {
    const caller = campaignScheduleRouter.createCaller(
      testContext(vi.fn(), session),
    );

    await expect(
      caller.override({
        campaignId,
        override: {
          kind: "cancelled",
          occurrenceStartAt: new Date("2026-08-09T23:00:00Z"),
        },
      }),
    ).rejects.toMatchObject({ code: "BAD_REQUEST" });
    expect(upsertCampaignOccurrenceOverride).not.toHaveBeenCalled();
  });

  it("allows an added occurrence even when there is no recurrence", async () => {
    vi.mocked(getCampaignForMemberById).mockResolvedValue({
      ...campaign,
      recurrence: null,
      recurrenceStartAt: null,
      recurrenceTimeZone: null,
      recurrenceDurationMinutes: null,
    } as never);
    vi.mocked(upsertCampaignOccurrenceOverride).mockResolvedValue({
      id: "override-1",
    } as never);
    const caller = campaignScheduleRouter.createCaller(
      testContext(vi.fn(), session),
    );

    await expect(
      caller.override({
        campaignId,
        override: {
          kind: "added",
          occurrenceStartAt: new Date("2026-08-09T23:00:00Z"),
          durationMinutes: 120,
        },
      }),
    ).resolves.toMatchObject({ id: "override-1" });
  });

  it("includes an occurrence moved from the recent past into the future", async () => {
    vi.mocked(listCampaignOccurrenceOverrides).mockResolvedValue([
      {
        campaignId,
        occurrenceStartAt: new Date("2026-08-08T23:00:00Z"),
        kind: "rescheduled",
        startsAt: new Date("2026-08-20T23:00:00Z"),
        durationMinutes: null,
      } as never,
    ]);

    const payload = await resolveCampaignSchedulePayload(
      {} as never,
      campaign,
      new Date("2026-08-10T00:00:00Z"),
    );

    expect(payload.occurrences).toContainEqual(
      expect.objectContaining({
        occurrenceStartAt: new Date("2026-08-08T23:00:00Z"),
        startsAt: new Date("2026-08-20T23:00:00Z"),
        state: "rescheduled",
      }),
    );
  });

  it("rejects an added occurrence that duplicates the recurrence", async () => {
    const caller = campaignScheduleRouter.createCaller(
      testContext(vi.fn(), session),
    );

    await expect(
      caller.override({
        campaignId,
        override: {
          kind: "added",
          occurrenceStartAt: startAt,
          durationMinutes: 120,
        },
      }),
    ).rejects.toMatchObject({ code: "BAD_REQUEST" });
    expect(upsertCampaignOccurrenceOverride).not.toHaveBeenCalled();
  });
});
